### ISSUE TITLE
V3 Upgrade: Cannot read properties of undefined (reading 'defineType')

### ISSUE THREAD

**Issue by 3200pro** [multiplehats/sveltekit-sanity-v3#2]
Hi,

Awesome work on this. I got it working well with the preview version of V3. I updated to V3 and for some reason I can't get past the following error:

`Cannot read properties of undefined (reading 'defineType')`

Any thoughts on what I am missing? Thanks!

**Comment by jakobbouchard** [comment]
If you disable ssr on the studio route, it should fix it :)

**Comment by 3200pro** [comment]
> If you disable ssr on the studio route, it should fix it :)

Thanks for the insight! I gave that a shot today. I noticed a little quirk. Initially I had `/studio` as my page route with `[...catchall]` within it.` /desk` is the primary work area within the sanity studio so a reload brought up another `404` since  `/desk` is unrecognized.

changing the` /studio` route to `/desk` seems to fix this.

**Comment by multiplehats** [comment]
> If you disable ssr on the studio route, it should fix it :)

Yep! The studio renders as an SPA. This should totally fix it.

More context here: https://kit.svelte.dev/docs/page-options#ssr

**Comment by 3200pro** [comment]
> https://kit.svelte.dev/docs/page-options#ssr

Did you try to refresh on the /desk URL ? If so, did it work on your end?

**Comment by multiplehats** [comment]
> > https://kit.svelte.dev/docs/page-options#ssr
> 
> 
> 
> Did you try to refresh on the /desk URL ? If so, did it work on your end?

Not sure what you mean. But I pushed an update to this repo yesterday where I got the error and have set ssr to false to fix the error.
